# Generated by Django 3.1.7 on 2021-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_top', models.ImageField(upload_to='logo_top')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='header_bg/')),
            ],
        ),
        migrations.CreateModel(
            name='FourthDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fourth_bg/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_left_title', models.CharField(max_length=100)),
                ('top_left_text', models.CharField(max_length=100)),
                ('top_right_title', models.CharField(max_length=100)),
                ('top_right_text', models.CharField(max_length=100)),
                ('bottom_left_title', models.CharField(max_length=100)),
                ('bottom_left_text', models.CharField(max_length=100)),
                ('bottom_right_title', models.CharField(max_length=100)),
                ('bottom_right_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='third_bg/')),
                ('text_image_1', models.ImageField(upload_to='text_image1')),
                ('text_image_2', models.ImageField(upload_to='text_image2')),
                ('text_image_3', models.ImageField(upload_to='text_image3')),
                ('text_image_4', models.ImageField(upload_to='text_image4')),
            ],
        ),
    ]
