# Generated by Django 3.1.7 on 2021-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
                ('link4', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
